#!/usr/bin/env python3

# The MIT License (MIT)

# Copyright (c) 2017 Lancaster University.

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

import os
import json
from natsort import natsorted

def getTags():
    tags = os.popen('git -P tag').read().strip().splitlines()
    tags = filter(lambda x: "-" not in x, tags)
    return natsorted(tags,reverse=True)

def getCommitsBetween( tagA, tagB = "HEAD" ):
    commits = os.popen(f"git -P shortlog {tagA}..{tagB}").read().strip().splitlines()
    return "\n".join(map( lambda x: x.replace("      ", " - "), commits ))

def getRepoURL():
    origin = os.popen("git remote get-url origin").read().strip().split( "github.com/", maxsplit=1 )
    return f"https://github.com/{origin[1]}/"

def printLibraryLinks():
    config = json.loads(open( 'target-locked.json' ).read())
    for lib in config['libraries']:
        print( F" - {lib['name']} = {lib['url']}/tree/{lib['branch']}" )

print( '# Changelog' )
print( '*This file is autogenerated and will be overwritten on the next tag.*' )
print( '' )
print( 'For official release notes, please see Releases.md' )
print( '' )
print( 'The current tag uses the following library versions:' )
printLibraryLinks()
print( '' )

tags = getTags()
for i in range(0, len(tags)-1):
    url = getRepoURL()
    logURL = f"{url}compare/{tags[i+1]}...{tags[i]}"
    treeURL = f"{url}tree/{tags[i]}"

    print('')
    print(f"## [{tags[i]}]({logURL})" )
    print('')
    print( getCommitsBetween( tags[i+1], tags[i] ) )
